### ISSUE TITLE
Default assets for ember do not seem to work

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-api#171] opened 2016-08-31 10:44 UTC
Not sure if we have yet to add them, or if it's just something that's broken. Didn't have time to do research. 

I'm talking `/icons/user_default_thumb.png`, etc.

**Comment by joshsmith** [comment] 2016-08-31 15:41
These were working fine for me, so that's surprising. Curious what the issue is.

**Comment by joshsmith** [comment] 2016-09-28 17:53
Closed in favor of #252.

**Closed as completed by joshsmith** 2016-09-28 17:53 UTC
Labels: bug, needs bug verification
